# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULAcode', '0021_auto_20170522_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='userRol',
            field=models.ManyToManyField(to='ULAcode.RolUsuario'),
        ),
    ]
