# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ULAcode', '0001_initial'), ('ULAcode', '0002_auto_20170516_1146'), ('ULAcode', '0003_auto_20170516_1149'), ('ULAcode', '0004_framework'), ('ULAcode', '0005_framework_frameworktoken'), ('ULAcode', '0006_auto_20170516_1201')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fotoPerfil', models.ImageField(upload_to='perfilUsuarios')),
                ('fotoAuth', models.ImageField(upload_to='authUsuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='rolUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=15, unique=True)),
                ('userToRol', models.ManyToManyField(to='ULAcode.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlFramework', models.CharField(max_length=50, unique=True)),
                ('frameworkActivo', models.BooleanField(default=False)),
                ('frameworkToken', models.CharField(default='empty', max_length=256)),
                ('userToFramework', models.ManyToManyField(to='ULAcode.Usuario')),
            ],
        ),
    ]
