# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULAcode', '0003_auto_20170516_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlFramework', models.CharField(max_length=50)),
                ('frameworkActivo', models.BooleanField(default=False)),
            ],
        ),
    ]
