# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULAcode', '0004_framework'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='frameworkToken',
            field=models.CharField(default='empty', max_length=256),
            preserve_default=False,
        ),
    ]
