# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ULAcode', '0007_auto_20170516_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='user',
            new_name='relUser',
        ),
    ]
