# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULAcode', '0009_auto_20170521_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolusuario',
            name='rol',
            field=models.CharField(max_length=15, unique=True, verbose_name='Rol del Usuario'),
        ),
    ]
