# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULAcode', '0010_auto_20170521_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolusuario',
            name='userToRol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='userRol',
            field=models.ManyToManyField(to='ULAcode.RolUsuario'),
        ),
    ]
