# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULAcode', '0011_auto_20170521_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framework',
            name='userToFramework',
        ),
        migrations.AddField(
            model_name='usuario',
            name='userToFramework',
            field=models.ManyToManyField(to='ULAcode.Framework'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='userRol',
            field=models.ManyToManyField(to='ULAcode.RolUsuario'),
        ),
    ]
