# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULAcode', '0017_auto_20170522_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='emailAdminFramework',
            field=models.EmailField(default='admin@ulacode.ula.ve', max_length=254, verbose_name='Email del Responsable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='userRol',
            field=models.ManyToManyField(to='ULAcode.RolUsuario'),
        ),
    ]
