# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULAcode', '0018_auto_20170530_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fotoAuth',
            field=models.ImageField(upload_to='', verbose_name='Foto para Autenticacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fotoPerfil',
            field=models.ImageField(upload_to='', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='userRol',
            field=models.ManyToManyField(to='ULAcode.RolUsuario'),
        ),
    ]
