# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULAcode', '0020_auto_20170531_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fotoAuth',
            field=models.ImageField(upload_to='authUsuario', verbose_name='Foto para Autenticacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fotoPerfil',
            field=models.ImageField(upload_to='perfilUsuarios', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='userRol',
            field=models.ManyToManyField(to='ULAcode.RolUsuario'),
        ),
    ]
